# Generated by Django 4.2.3 on 2023-09-01 00:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0002_alter_news_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="created_at",
            field=models.DateField(auto_now=True),
        ),
    ]
